name: Runs CI for this application

on:
  push:
    branches:
      - master
      - test
  pull_request:
  workflow_dispatch:
    inputs:
      python-version:
        type: string
        description: "Defines python version for workflow"
        default: "3.8"
# defaults:
#   run:
#     shell: bash
#     working-directory: ./app
jobs:
  # lint-check:
  #   runs-on: ubuntu-latest

    
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Build test runner docker image
  #       run: docker compose build test-runner
  #     - name: Run lint check
  #       run: docker compose up --abort-on-container-exit test-runner

  lint-check-native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install flake8
        run: pip install flake8==7.1.1
      - name: Run flake8 on changed files
        run: |
          git fetch origin/test ${{ github.head_ref }} --depth=1
          CHANGED_FILES=$(git diff --name-only origin/${{ github.head_ref }})
          echo $CHANGED_FILES

 

  # unit-test:a
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install python 3.8
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.8'
  #     - name: Install pytest package
  #       run: |
  #         pip install -r requirements.txt
  #         pip install pytest
  #     - name: Run unit tests
  #       run: pytest tests/
  
  # server-build:
  #     runs-on: ubuntu-latest
  #     needs:
  #       - unit-test
  #     steps:
  #       - uses: actions/checkout@v4
  #       - name: Login to Docker Hub
  #         uses: docker/login-action@v3
  #         with:
  #           username: ${{ vars.DOCKERHUB_USERNAME }}
  #           password: ${{ secrets.DOCKERHUB_TOKEN }}
  #       - name: Set up QEMU
  #         uses: docker/setup-qemu-action@v3
  #       - name: Set up Docker Buildx
  #         uses: docker/setup-buildx-action@v3
  #       - name: Build and push
  #         uses: docker/build-push-action@v6
  #         with:
  #           push: true
  #           tags: user/app:latest
