name: Runs CI for this application
on:
  push:
    branches:
        - master
        - "test/**"
  # pull_request:
  #   # types:
  #   #   - "opened"
  #   #   - "edited"
  
  # - push
  # - pull_request


jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build test runner docker image
        run: docker compose build test-runner
      - name: Run unit tests
        run: docker compose up --abort-on-container-exit test-runner

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install pytest package
        run: |
          pip install -r requirements.txt
          pip install pytest
      - name: Run unit tests
        run: pytest tests/
  
  # server-build:
  #     runs-on: ubuntu-latest
  #     needs:
  #       - unit-test
  #     steps:
  #       - uses: actions/checkout@v4
  #       - name: Login to Docker Hub
  #         uses: docker/login-action@v3
  #         with:
  #           username: ${{ vars.DOCKERHUB_USERNAME }}
  #           password: ${{ secrets.DOCKERHUB_TOKEN }}
  #       - name: Set up QEMU
  #         uses: docker/setup-qemu-action@v3
  #       - name: Set up Docker Buildx
  #         uses: docker/setup-buildx-action@v3
  #       - name: Build and push
  #         uses: docker/build-push-action@v6
  #         with:
  #           push: true
  #           tags: user/app:latest
